vocab/urls.py
from django.conf.urls import url, include
from . import views

terms = [
    url(r'^edit/$', views.EditTermView.as_view(), name='edit_term'),
    url(r'^list/$', views.TermListCreateView.as_view(), name='list_create'),
    url(r'^detail/(?P<pk>[0-9])/$', views.TermDetailView.as_view(),
        name='detail'),
]

relationships = [
    url(r'^list/$', views.RelationshipListCreateView.as_view(),
        name='list_create'),
    url(r'^detail/(?P<pk>[0-9])/$', views.RelationshipDetailView.as_view(),
        name='detail'),
]

domains = [
    url(r'^list/$', views.DomainListCreateView.as_view(), name='list_create'),
    url(r'^detail/(?P<pk>[0-9])/$', views.DomainDetailView.as_view(),
        name='detail'),
]

triples = [
    url(r'^list/$', views.TripleListCreateView.as_view(),
        name='list_create'),
    url(r'^detail/(?P<pk>[0-9])/$', views.TripleDetailView.as_view(),
        name='detail'),
]

urlpatterns = [
    url(r'^$', views.MainPageView.as_view(), name='main_page'),
    url(r'^graph/$', views.VocabGraphView.as_view(), name='vocab_graph'),
    url(r'^graph/frame/', views.GraphView.as_view(), name='graph'),
    url(r'^terms/', include(terms, namespace='terms')),
    url(r'^relationships/', include(relationships, namespace='relationships')),
    url(r'^domains/', include(domains, namespace='domains')),
    url(r'^triples/', include(triples, namespace='triples')),
    url(r'^pending/$', views.PendingView.as_view(), name='pending'),
]

vocabulary_harmonizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from common.views import AboutView, MainView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vocab/', include('vocab.urls', namespace='vocab')),
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},
        name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logout.html'},
        name='logout'),
    url(r'^$', MainView.as_view(), name='main'),
]

common/models.py
from __future__ import unicode_literals

from django.db import models


class License(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField()

    def __str__(self):
        return self.name


class Organization(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

common/views.py
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework import status


class MainView(generics.RetrieveAPIView):
    renderer_classes = (TemplateHTMLRenderer, )

    def get(self, request, *args, **kwargs):
        params = {

        }
        return Response(params, template_name='common/main.html',
                        status=status.HTTP_200_OK)


class AboutView(generics.RetrieveAPIView):
    renderer_classes = (TemplateHTMLRenderer, )

    def get(self, request, *args, **kwargs):
        params = {

        }
        return Response(params, template_name='common/about.html',
                        status=status.HTTP_200_OK)

common/templates/common/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'common/js/about.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col s12">
            <h4>Project</h4>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p>Some words here about the project.</p>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <h4>Acknowledgments</h4>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p>Some people who were involved.</p>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <h4>Contact</h4>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p>Some ways to complain.</p>
        </div>
    </div>
{% endblock %}

common/templates/common/main.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
<script type="text/javascript" src="{% static 'common/js/main.js' %}"></script>
{% endblock %}
{% block navbar %}
<nav class="white">
    <div class="nav-wrapper">
        <a href="//{{ request.get_host }}{% url 'main' %}" class="brand-logo blue-text text-darken-4">VocabularyHarmonizer</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a  class="blue-text text-darken-4" href="//{{ request.get_host }}{% url 'about' %}">About</a></li>
            {% if user.is_anonymous %}
                <li><a class="blue-text text-darken-4" href="//{{ request.get_host }}{% url 'login' %}">Log in</a></li>
            {% else %}
                <li><a class="blue-text text-darken-4" href="//{{ request.get_host }}{% url 'vocab:pending' %}">Pending</a></li>
                <li><a class="blue-text text-darken-4" href="#">{{ user.first_name }}</a></li>
                <li><a class="blue-text text-darken-4" href="//{{ request.get_host }}{% url 'logout' %}">log out</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col s6 offset-s3 center-align white-text">
        <br />
        <br />
        <br />
        <h5>VOCABULARY HARMONIZER is a tool for bridging large and small vocabularies and
        aligning them for collaboration, research, and development</h5>
    </div>
</div>
<div class="row">
    <div class="col s4 offset-s1">
        <div class="row">
            <div class="col s8 offset-s2">
                <a href="//{{ request.get_host }}{% url 'vocab:main_page' %}"><div class="circle orange lighten-1 hoverable home-circle true-horizontal-center"><i class="material-icons black-text true-center" style="font-size: 10rem;">translate</i></div></a>
            </div>
        </div>
        <div class="row">
            <div class="col s12 center-align">
                <h4 class="white-text">Domains & Vocabulary</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s12 center-align white-text">
                <h5>View, manage, and edit domains and their vocabularies</h5>
            </div>
        </div>
    </div>
    <div class="col s4 offset-s2">
        <div class="row">
            <div class="col s8 offset-s2">
                <a href="//{{ request.get_host }}{% url 'vocab:vocab_graph' %}"><div class="circle purple hoverable home-circle true-horizontal-center"><i class="material-icons black-text true-center" style="font-size: 10rem;">insert_chart</i></div></a>
            </div>
        </div>
        <div class="row">
            <div class="col s12 center-align">
                <h4 class="white-text">Visualize</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s12 center-align">
                <h5 class="white-text">Visualize the relationships between domains and vocabularies</h5>
                </div>
            </div<
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
<footer class="page-footer white">
    <div class="footer-copyright">
        <div class="container black-text center-align">
            Unless otherwise noted, all content on this website is licensed under a <a class="grey-text text-darken-2" rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
        </div>
    </div>
</footer>
{% endblock %}